export type Wave = { label: string; n: number; headers: string[]; rows: string[][] };
export type Survey = { id: string; title: string; n: number; window: string; note: string; waves: Wave[] };
export const SURVEYS: Survey[] = [
  {
    "id": "wishlist",
    "title": "User Research Survey",
    "n": 16,
    "window": "20-29 August 2026",
    "note": "Run in two waves. The three pilot responses use slightly looser question wording (“it” rather than “your wishlist”); the thirteen final responses use the clarified wording. Both waves are shown separately below.",
    "waves": [
      {
        "label": "Pilot wave",
        "n": 3,
        "headers": [
          "Timestamp",
          "How often do you shop for clothes on Myntra?",
          "How many items are in it right now?",
          "In the last 30 days, how many times did you open it?",
          "In the last 30 days, did you buy anything FROM it?",
          "Why did you save it rather than buy it?",
          "What's the single biggest thing stopping you?",
          "Did you try to find that out? Tick everywhere you looked.",
          "What would you need to know to decide today - buy it, or delete it?",
          "The last time you removed something from your wishlist without buying it, why?",
          "When two or three saved items are close alternatives, what usually happens?",
          "Across your whole wishlist, which of these are true of at least one item?",
          "Age",
          "Which city?"
        ],
        "rows": [
          [
            "2026/08/20 11:05:16 AM GMT+5:30",
            "A few times a month",
            "More than 30",
            "2-3 times",
            "No",
            "I wanted it, but wasn't sure about something (size, fabric, whether it'd suit me)",
            "Not sure it'll fit / which size to order",
            "I tried, and still couldn't find out",
            "Whether the shoulders will be too wide on me.The photos tell me nothing. If someone my height had posted a picture, or if it just told me how it fitted people who ordered my usual size.",
            "I couldn't find out enough about it to decide",
            "I go back and forth and end up buying none of them",
            "I'm not sure it'll fit me;I'm not sure about the fabric or quality;I'm not sure it'll suit me or my body type;I don't fully trust the seller or brand;I'm waiting for the price to drop;I'm saving it for an occasion",
            "25-32",
            "Pune"
          ],
          [
            "2026/08/20 12:42:21 PM GMT+5:30",
            "A few times a year",
            "6-15",
            "4-10 times",
            "No",
            "I wanted it, but wasn't sure about something (size, fabric, whether it'd suit me)",
            "I don't trust the seller or brand",
            "I tried, and still couldn't find out",
            "Whether this brand is actually any good or it's just a random seller. The reviews contradict each other and half look fake. If I knew someone real had bought it and it wasn't rubbish, I'd order.",
            "I stopped trusting it would be right - fit, fabric or quality",
            "I go looking for more options instead of choosing",
            "I'm not sure about the fabric or quality;I'm not sure it'll look like the photos;I don't fully trust the seller or brand",
            "18-24",
            "Indore"
          ],
          [
            "2026/08/20 12:45:50 PM GMT+5:30",
            "Every month or two",
            "More than 30",
            "More than 10 times",
            "Yes, more than one",
            "I was waiting for the price to drop, or for a sale",
            "I'm waiting for a sale",
            "I didn't try",
            "Nothing really. I know what I want, I just want it at the right price. Tell me when it drops and I'll buy it.",
            "The price never came down enough",
            "I pick one fairly quickly",
            "I'm waiting for the price to drop;I'm saving it for an occasion",
            "25-32",
            "Delhi"
          ]
        ]
      },
      {
        "label": "Main wave",
        "n": 13,
        "headers": [
          "Timestamp",
          "How often do you buy clothes on Myntra?",
          "How many items are in it right now?",
          "In the last 30 days, how many times did you open your wishlist?",
          "In the last 30 days, did you buy anything from your wishlist?",
          "Why did you save that item rather than buy it?",
          "What's the single biggest thing stopping you from buying that item?",
          "Did you try to find that out? Tick everywhere you looked.",
          "What would you need to know to decide on that item today - buy it, or delete it?",
          "The last time you removed something from your wishlist without buying it, why?",
          "When two or three saved items are close alternatives, what usually happens?",
          "Across your whole wishlist, which of these are true of at least one item?",
          "Age",
          "Which city?"
        ],
        "rows": [
          [
            "2026/08/20 2:58:47 PM GMT+5:30",
            "Never - I don't shop on Myntra",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          [
            "2026/08/20 4:56:55 PM GMT+5:30",
            "A few times a month",
            "I don't have a wishlist",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "25-32",
            "Khammam "
          ],
          [
            "2026/08/20 6:02:04 PM GMT+5:30",
            "A few times a year",
            "16-30",
            "2-3 times",
            "No",
            "I was waiting for the price to drop, or for a sale",
            "I'm waiting for a sale",
            "I tried, and still couldn't find out",
            "Reviews ",
            "I found something better, here or elsewhere",
            "I go back and forth and end up buying none of them",
            "I'm not sure it'll look like the photos;I'm waiting for the price to drop",
            "25-32",
            ""
          ],
          [
            "2026/08/20 10:56:45 PM GMT+5:30",
            "A few times a year",
            "More than 30",
            "Once",
            "No",
            "I was waiting for the price to drop, or for a sale",
            "Costs more than I want to spend right now",
            "The size chart on the product page;The ratings / fit feedback on the listing",
            "Price ",
            "I've never removed anything without buying it",
            "This doesn't really happen to me",
            "I'm not sure about the fabric or quality;I'm not sure it'll suit me or my body type;I'm waiting for the price to drop",
            "25-32",
            "Bengaluru "
          ],
          [
            "2026/08/21 4:17:00 PM GMT+5:30",
            "A few times a year",
            "16-30",
            "Not once",
            "I don't remember",
            "I was waiting for the price to drop, or for a sale",
            "Costs more than I want to spend right now",
            "I didn't try",
            "Urgent need,price drop or not",
            "I no longer needed it",
            "I pick one fairly quickly",
            "I'm not sure it'll fit me",
            "25-32",
            ""
          ],
          [
            "2026/08/23 7:23:36 PM GMT+5:30",
            "Every month or two",
            "6-15",
            "2-3 times",
            "Yes, more than one",
            "I was waiting for the price to drop, or for a sale",
            "I'm waiting for a sale",
            "The reviews or customer photos;The ratings / fit feedback on the listing;Searched YouTube or Instagram for it;Planned to order two sizes and return one",
            "if i get a notification of price drop",
            "The price never came down enough",
            "I go back and forth for a while, then buy one",
            "I'm not sure about the fabric or quality;I'm not sure it'll look like the photos;I don't fully trust the seller or brand",
            "18-24",
            ""
          ],
          [
            "2026/08/24 7:15:16 PM GMT+5:30",
            "A few times a year",
            "1-5",
            "Not once",
            "No",
            "I was waiting for the price to drop, or for a sale",
            "I'm waiting for a sale",
            "Checked the brand's own site, or another app",
            "Fine",
            "I no longer needed it",
            "I go back and forth for a while, then buy one",
            "I don't fully trust the seller or brand",
            "25-32",
            "Bangalore"
          ],
          [
            "2026/08/24 7:33:48 PM GMT+5:30",
            "A few times a year",
            "1-5",
            "Not once",
            "No",
            "I honestly don't remember",
            "I'd forgotten about it until now",
            "I didn't try",
            "My need of having that item, if I dont need it today I will not buy it",
            "I no longer needed it",
            "I pick one fairly quickly",
            "I'm not sure about the fabric or quality;I'm not sure it'll look like the photos;I'm not sure it'll suit me or my body type",
            "25-32",
            "Raipur,Chhattisgarh"
          ],
          [
            "2026/08/25 4:42:50 PM GMT+5:30",
            "Every month or two",
            "1-5",
            "Not once",
            "No",
            "I was saving it for an occasion coming up",
            "Can't decide between this and something else",
            "The reviews or customer photos;The ratings / fit feedback on the listing;Planned to order two sizes and return one;I tried, and still couldn't find out",
            "Easy returns low prices and good options for every occasion",
            "I changed my mind about wanting it",
            "I go looking for more options instead of choosing",
            "I'm waiting for the price to drop;I'm saving it for an occasion",
            "25-32",
            "Bangalore"
          ],
          [
            "2026/08/25 10:39:34 PM GMT+5:30",
            "Every month or two",
            "1-5",
            "Not once",
            "No",
            "I was waiting for the price to drop, or for a sale",
            "I'm waiting for a sale",
            "The size chart on the product page;The reviews or customer photos",
            "When is the sale ",
            "The price never came down enough",
            "I pick one fairly quickly",
            "I'm waiting for the price to drop",
            "33-40",
            "Mumbai "
          ],
          [
            "2026/08/28 7:35:49 PM GMT+5:30",
            "A few times a year",
            "16-30",
            "Not once",
            "No",
            "I was waiting for the price to drop, or for a sale",
            "Not sure about the fabric or quality",
            "I didn't try;The reviews or customer photos",
            "Price ",
            "It went out of stock, or my size did",
            "I go back and forth for a while, then buy one",
            "I'm not sure about the fabric or quality;I'm not sure it'll look like the photos",
            "18-24",
            "Bangalore "
          ],
          [
            "2026/08/29 4:16:24 PM GMT+5:30",
            "A few times a year",
            "More than 30",
            "4-10 times",
            "No",
            "I wanted it, but wasn't sure about something (size, fabric, whether it'd suit me)",
            "Not sure it'll suit me or my body type",
            "The reviews or customer photos;The ratings / fit feedback on the listing;Searched YouTube or Instagram for it",
            "How it would look on me",
            "I've never removed anything without buying it",
            "I go looking for more options instead of choosing",
            "I'm not sure it'll fit me;I'm not sure about the fabric or quality;I'm not sure it'll suit me or my body type",
            "25-32",
            "Bangalore"
          ],
          [
            "2026/08/29 11:52:20 PM GMT+5:30",
            "A few times a year",
            "1-5",
            "Once",
            "No",
            "I was saving it for an occasion coming up",
            "Returning it would be a hassle if it's wrong",
            "The reviews or customer photos",
            "The quality of the product from the real customers. ",
            "I found something better, here or elsewhere",
            "This doesn't really happen to me",
            "I'm not sure about the fabric or quality;I don't fully trust the seller or brand",
            "25-32",
            "Tier 1 "
          ]
        ]
      }
    ]
  },
  {
    "id": "prototype",
    "title": "Prototype Study",
    "n": 11,
    "window": "1-4 September 2026",
    "note": "Two rounds on the live prototype. Round two rephrased several questions in plainer language and added feature notes, so rating scales are reported per round rather than pooled. Categorical answers are comparable across both.",
    "waves": [
      {
        "label": "Round one",
        "n": 5,
        "headers": [
          "Timestamp",
          "Did you find something you Saved/Wishlisted earlier while searching?",
          "Did you understand why it appeared?",
          "Did you find anything confusing about this Feature?",
          "After Opening the Wishlisted Item on the Screen, scrolling down your items did that feature influence your Buying Decision ?",
          "Was that enough to decide, or would you still check elsewhere?",
          "This screen cleared up what I was unsure about.",
          "Compared to what page 1 described, was this screen...",
          "What would you still need to know about your Wishlisted Item before you'd buy it or delete it?",
          "What's the main thing still holding you back on this item?",
          "If your size or item wasn't available, was it clear what to do next?",
          "What happened when you tapped to buy or save it?",
          "\"Buy from Wishlist\" or \"Compare options\" - which did you notice or tap first, and why?",
          "If you compared two items, did sorting them by what mattered to you actually help?",
          "If a \"complete the look\" or pairing suggestion appeared, was it useful?",
          "Overall, this was useful to me on its own.",
          "One sentence: what would make this actually useful for you?",
          "On your real wishlists (not this demo), what actually brings you back to look at a saved item?",
          "Age",
          "Which city?"
        ],
        "rows": [
          [
            "2026/09/01 5:12:16 PM GMT+5:30",
            "Yes, easily",
            "Yes, clearly",
            "",
            "4",
            "Good enough to decide",
            "4",
            "About what I expected",
            "Any Discounts ",
            "Still thinking about the price",
            "Yes, totally clear",
            "It opened next steps or choices for me to pick from",
            "Buy From Wishlist",
            "Yes, it helped me decide",
            "Yes, it suggested something I'd actually pair it with",
            "4",
            "",
            "I mostly don't go back to things I've saved",
            "25-32",
            "Bangalore"
          ],
          [
            "2026/09/01 5:16:11 PM GMT+5:30",
            "Yes, easily",
            "Sort of",
            "It said 'good match' but didn't say why, or whether it'd actually fit someone my height",
            "3",
            "Helped, but I'd still check somewhere else",
            "3",
            "Less than I expected",
            "Whether the shoulders will be too wide on me — like on my usual size",
            "Not sure it will fit me",
            "Yes, totally clear",
            "It opened next steps or choices for me to pick from",
            "",
            "I didn't compare two items",
            "It appeared but didn't feel relevant",
            "3",
            "Show me people my height who kept this size",
            "I go looking on my own, without any reminder",
            "18-24",
            "Pune"
          ],
          [
            "2026/09/01 5:20:59 PM GMT+5:30",
            "Yes, but I had to look for it",
            "Yes, clearly",
            "",
            "4",
            "Helped, but I'd still check somewhere else",
            "3",
            "About what I expected",
            "Just which of the two I saved is actually better — right now I can't tell",
            "Too many similar options, can't tell them apart",
            "I didn't run into this",
            "It opened next steps or choices for me to pick from",
            "Compare options — I always want to see alternatives before I commit to one",
            "Yes, it helped me decide",
            "Yes, it suggested something I'd actually pair it with",
            "4",
            "Let me save my 'winner' after comparing so I don't have to redo it next time",
            "Someone else mentions it or sends me something similar",
            "25-32",
            "Bangalore"
          ],
          [
            "2026/09/02 12:03:01 AM GMT+5:30",
            "Yes, easily",
            "Sort of",
            "The removed item from wishlist still appeared in the search as wishlisted item.",
            "4",
            "Good enough to decide",
            "3",
            "More than I expected",
            "I will like to know if there is new collection added to the inventory which may be better looking than my wishlisted one. ",
            "Could get out of style if it was in wishlist for too long",
            "I didn't run into this",
            "It opened next steps or choices for me to pick from",
            "",
            "Yes, it helped me decide",
            "Yes, it suggested something I'd actually pair it with",
            "3",
            "",
            "I go looking on my own, without any reminder;I mostly don't go back to things I've saved",
            "33-40",
            "Bangalore"
          ],
          [
            "2026/09/02 10:56:49 AM GMT+5:30",
            "Yes, easily",
            "Sort of",
            "Old items saved long back was also shown. I would love to see newly added items in the beginning than the old ones",
            "4",
            "Good enough to decide",
            "4",
            "I didn't read page 1 closely",
            "I would love to see the complete the look option with my saved items as well. Would like to know which items it will look good with . ",
            "How it will pair with others .",
            "Confusing",
            "Not sure / don't remember",
            "Buy from wishlist. ",
            "I didn't compare two items",
            "Yes, it suggested something I'd actually pair it with",
            "5",
            "",
            "I mostly don't go back to things I've saved",
            "25-32",
            "Bangalore"
          ]
        ]
      },
      {
        "label": "Round two",
        "n": 6,
        "headers": [
          "Timestamp",
          "When you searched, did anything from your wishlist come up?",
          "Was it something you added, or something already in the wishlist?",
          "Was it clear why those items came up?",
          "Was anything about it confusing?",
          "How sure were you about whether to buy it?",
          "Was that enough to decide, or would you check somewhere else first?",
          "I had a doubt about the item, and this answered it.",
          "We listed what this app is meant to do. What you saw was:",
          "What's the main thing stopping you from buying it?",
          "What would the app have to show you to settle that?",
          "If your size or the item was gone, was it clear what to do next?",
          "When you added it to your bag, what happened?",
          "Which did you notice first, \"Buy from Wishlist\" or \"Compare options\"?",
          "Why that one?",
          "On the compare screen you could tap fit, delivery, reviews and so on to reorder things. Did that help you decide?",
          "If you saw \"Style it with your saved items\", was it any good?",
          "This would be useful to me when I shop.",
          "What would make it genuinely useful to you?",
          "On your own wishlist, not this demo: what actually makes you go back to something you saved?",
          "Age",
          "Which city?"
        ],
        "rows": [
          [
            "2026/09/03 3:33:04 PM GMT+5:30",
            "Yes, I spotted it right away",
            "Something I added",
            "Yes, clear",
            "",
            "4",
            "Helped, but I'd still check elsewhere",
            "",
            "About what we said",
            "The price",
            "",
            "Yes, totally clear",
            "It just showed a confirmation",
            "Buy from Wishlist",
            "",
            "Yes, it helped",
            "Yes, I'd actually put those together",
            "5",
            "",
            "A notification or price-drop alert",
            "25-32",
            "Pune"
          ],
          [
            "2026/09/03 3:36:22 PM GMT+5:30",
            "Yes, I spotted it right away",
            "Something I added",
            "Sort of",
            "",
            "3",
            "Helped, but I'd still check elsewhere",
            "4",
            "About what we said",
            "The price",
            "Price Drop alert after the item was Wishlisted",
            "Sort of clear",
            "It just showed a confirmation",
            "Compare options",
            "",
            "Yes, it helped",
            "Yes, I'd actually put those together",
            "5",
            "",
            "A notification or price-drop alert",
            "25-32",
            "Pune"
          ],
          [
            "2026/09/03 3:39:52 PM GMT+5:30",
            "Yes, I spotted it right away",
            "Both",
            "Yes, clear",
            "There are already items in the Wishlist and I found items which I saved too.",
            "5",
            "Enough to decide",
            "5",
            "Better than we said",
            "Nothing, I'd be happy to buy it",
            "Price Drop would be useful ",
            "Yes, totally clear",
            "It just showed a confirmation",
            "Buy from Wishlist",
            "",
            "Yes, it helped",
            "Yes, I'd actually put those together",
            "5",
            "",
            "A notification or price-drop alert;I go and look on my own",
            "18-24",
            "Bangalore"
          ],
          [
            "2026/09/03 6:46:58 PM GMT+5:30",
            "Yes, I spotted it right away",
            "Something I added",
            "Sort of",
            "",
            "4",
            "Helped, but I'd still check elsewhere",
            "4",
            "About what we said",
            "The price",
            "",
            "Yes, totally clear",
            "It just showed a confirmation",
            "Buy from Wishlist",
            "",
            "Yes, it helped",
            "Yes, I'd actually put those together",
            "4",
            "",
            "A notification or price-drop alert;I go and look on my own",
            "25-32",
            "Bangalore"
          ],
          [
            "2026/09/04 11:18:59 AM GMT+5:30",
            "Yes, I spotted it right away",
            "Something I added",
            "Yes, clear",
            "",
            "4",
            "Helped, but I'd still check elsewhere",
            "3",
            "I don't remember that list",
            "I don't know what it goes with",
            "",
            "This didn't happen to me",
            "I don't remember",
            "Buy from Wishlist",
            "",
            "Yes, it helped",
            "Yes, I'd actually put those together",
            "4",
            "",
            "I mostly don't go back",
            "25-32",
            ""
          ],
          [
            "2026/09/04 12:42:09 PM GMT+5:30",
            "Yes, I spotted it right away",
            "Something already there",
            "Yes, clear",
            "",
            "2",
            "I'd mostly have to look elsewhere",
            "",
            "Less than we said",
            "Not sure it's genuine or good quality",
            "",
            "Confusing",
            "I don't remember",
            "Buy from Wishlist",
            "",
            "Yes, it helped",
            "I didn't see one",
            "2",
            "",
            "A notification or price-drop alert",
            "25-32",
            "Raipur"
          ]
        ]
      }
    ]
  }
];
